name = "aryan7"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "211.230.110.231:50008"
UUID = "1c1f82e6-5545-4afb-b002-6b788aab44c4"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
